version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.2

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys

      - run:
          name: Keyscan (HACK)
          command: ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

      - run:
          name: Install rsync
          command: sudo apt-get update -qq && sudo apt-get install -y rsync

      - run:
          name: Deploy to server
          command: rsync -r --delete-after --quiet ~/repo/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_FOLDER
